import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { safeCell, toCsv, type Table } from "@/lib/export";

/** CSV for several tables: each one keeps its own header; they are separated by a blank line. */
export function tablesToCsv(tables: Table[]): string {
  return tables.length === 1
    ? toCsv(tables[0])
    : tables.map((t) => `${safeCell(t.title)}\r\n${toCsv(t).replace("﻿", "")}`).join("\r\n").replace(/^/, "﻿");
}

export async function tablesToXlsx(tables: Table[], meta: { title: string }): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "MarketplacePH";
  wb.created = new Date();
  for (const t of tables) {
    const ws = wb.addWorksheet(t.title.replace(/[\\/*?:[\]]/g, " ").slice(0, 31) || "Sheet");
    ws.addRow([meta.title]).font = { bold: true, size: 14 };
    if (t.subtitle) ws.addRow([t.subtitle]).font = { italic: true };
    ws.addRow([]);
    const head = ws.addRow(t.columns);
    head.font = { bold: true, color: { argb: "FFFFFFFF" } };
    head.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0B4FD1" } };
    // text is neutralised against formula injection; numbers stay numbers (and are formatted as pesos in "amount" columns)
    for (const r of t.rows) ws.addRow(r.map((c) => safeCell(c)));
    if (t.totals) ws.addRow(t.totals.map((c) => safeCell(c))).font = { bold: true };
    t.columns.forEach((name, i) => {
      const col = ws.getColumn(i + 1);
      col.width = Math.min(48, Math.max(12, name.length + 4, ...t.rows.map((r) => String(r[i] ?? "").length + 2)));
      if (/amount|total|spent|revenue|fee|income|expense|price/i.test(name)) col.numFmt = '"₱"#,##0.00';
    });
  }
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Simple, readable PDF (Helvetica has no peso sign, so amounts print as "PHP"). */
export async function tablesToPdf(tables: Table[], meta: { title: string; subtitle: string }): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 36, info: { Title: meta.title, Author: "MarketplacePH" } });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));
  const text = (v: unknown) => String(safeCell(v as never)).replaceAll("₱", "PHP ");

  doc.fontSize(18).fillColor("#06308f").text("MarketplacePH", { continued: true }).fillColor("#f97316").text("  " + meta.title);
  doc.moveDown(0.2).fontSize(9).fillColor("#475569").text(meta.subtitle);

  for (const t of tables) {
    doc.moveDown(1).fontSize(12).fillColor("#06308f").text(t.title);
    if (t.subtitle) doc.fontSize(8).fillColor("#475569").text(t.subtitle);
    doc.moveDown(0.4);
    const width = doc.page.width - 72;
    const colW = width / t.columns.length;
    const drawRow = (cells: unknown[], bold = false, fill?: string) => {
      const y = doc.y;
      const h = Math.max(...cells.map((c) => doc.heightOfString(text(c), { width: colW - 6, lineBreak: true })), 12) + 6;
      if (y + h > doc.page.height - 50) { doc.addPage(); return drawRow(cells, bold, fill); }
      if (fill) doc.rect(36, y, width, h).fill(fill);
      doc.fillColor(fill ? "#ffffff" : "#0f172a").font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(8.5);
      cells.forEach((c, i) => doc.text(text(c), 36 + i * colW + 3, y + 3, { width: colW - 6 }));
      doc.y = y + h;
      doc.x = 36;
    };
    drawRow(t.columns, true, "#0b4fd1");
    t.rows.forEach((r) => drawRow(r));
    if (t.totals) drawRow(t.totals, true);
    if (!t.rows.length) doc.fillColor("#475569").fontSize(9).text("No entries in this period.");
  }
  doc.moveDown(1.5).fontSize(7.5).fillColor("#64748b").text("Generated by MarketplacePH. This is a simple record of your own data, not accounting or tax advice. Consult an accountant for official books and filings.", 36, doc.y, { width: doc.page.width - 72 });
  doc.end();
  return done;
}
